2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_setup.py:_flush():67] Configure stats pid to 31175
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_setup.py:_flush():67] Loading settings from /home/bhanu/.config/wandb/settings
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_setup.py:_flush():67] Loading settings from /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/settings
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/run-20250306_120643-7tx0yrh2/logs/debug.log
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/run-20250306_120643-7tx0yrh2/logs/debug-internal.log
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:init():761] calling init triggers
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:init():784] starting backend
2025-03-06 12:06:43,458 INFO    MainThread:31175 [wandb_init.py:init():788] sending inform_init request
2025-03-06 12:06:43,465 INFO    MainThread:31175 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-06 12:06:43,466 INFO    MainThread:31175 [wandb_init.py:init():798] backend started and connected
2025-03-06 12:06:43,473 INFO    MainThread:31175 [wandb_init.py:init():891] updated telemetry
2025-03-06 12:06:43,508 INFO    MainThread:31175 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-06 12:06:44,036 ERROR   MainThread:31175 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity ce21b031 not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-06 12:06:45,036 INFO    MsgRouterThr:31175 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
