2025-03-17 16:53:44,761 INFO    MainThread:14490 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-17 16:53:44,761 INFO    MainThread:14490 [wandb_setup.py:_flush():67] Configure stats pid to 14490
2025-03-17 16:53:44,761 INFO    MainThread:14490 [wandb_setup.py:_flush():67] Loading settings from /home/bhanu/.config/wandb/settings
2025-03-17 16:53:44,761 INFO    MainThread:14490 [wandb_setup.py:_flush():67] Loading settings from /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/settings
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/run-20250317_165344-ixudtegp/logs/debug.log
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/bhanu/IITM/Courses/FDL/da6401_assignment1/wandb/run-20250317_165344-ixudtegp/logs/debug-internal.log
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_init.py:init():761] calling init triggers
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-17 16:53:44,762 INFO    MainThread:14490 [wandb_init.py:init():784] starting backend
2025-03-17 16:53:44,763 INFO    MainThread:14490 [wandb_init.py:init():788] sending inform_init request
2025-03-17 16:53:44,770 INFO    MainThread:14490 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-17 16:53:44,770 INFO    MainThread:14490 [wandb_init.py:init():798] backend started and connected
2025-03-17 16:53:44,773 INFO    MainThread:14490 [wandb_init.py:init():891] updated telemetry
2025-03-17 16:53:44,791 INFO    MainThread:14490 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-17 16:53:45,245 INFO    MainThread:14490 [wandb_init.py:init():990] starting run threads in backend
2025-03-17 16:53:45,654 INFO    MainThread:14490 [wandb_run.py:_console_start():2375] atexit reg
2025-03-17 16:53:45,654 INFO    MainThread:14490 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-17 16:53:45,655 INFO    MainThread:14490 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-17 16:53:45,655 INFO    MainThread:14490 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-17 16:53:45,657 INFO    MainThread:14490 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-17 16:53:56,658 INFO    MsgRouterThr:14490 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-17 16:53:58,346 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,364 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,368 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,370 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,371 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,373 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,375 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,377 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,378 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,379 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,382 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,384 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,385 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,387 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,388 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 16:53:58,389 ERROR   MainThread:14490 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bhanu/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
